OPTION_SPICY = "辣度"
OPTION_GARLIC = "加蒜"
OPTION_BASIL = "九層塔"
OPTION_CUT = "切"

SYSTEM_OPTION_NAMES = [OPTION_SPICY, OPTION_GARLIC, OPTION_BASIL, OPTION_CUT]

# 系統選項固定 ID（依 migration seed 順序，不可異動）
SPICY_OPTION_ID = 1
GARLIC_OPTION_ID = 2
BASIL_OPTION_ID = 3
CUT_OPTION_ID = 4

SYSTEM_OPTION_IDS = [SPICY_OPTION_ID, GARLIC_OPTION_ID, BASIL_OPTION_ID, CUT_OPTION_ID]
