EXTRA_INGREDIENT_COST = 10  # 每份加料（加蒜／九層塔）單價（元）

OPTION_SPICY = "辣度"
OPTION_GARLIC = "加蒜"
OPTION_BASIL = "九層塔"
OPTION_CUT = "切"

SYSTEM_OPTION_NAMES = [OPTION_SPICY, OPTION_GARLIC, OPTION_BASIL, OPTION_CUT]
