# Generated by Django 6.0.3 on 2026-04-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
