# Generated by Django 6.0.3 on 2026-04-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='file_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
