# Generated by Django 6.0.3 on 2026-04-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_menu_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='file_path',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
