# Generated by Django 6.0.3 on 2026-04-01 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_alter_menu_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='opt_group_id',
        ),
    ]
