# Generated by Django 5.1.6 on 2026-04-16 15:16

from django.db import migrations, models


def migrate_employee_identity(apps, schema_editor):
    """將現有資料庫中 identity='B' 的使用者改為 'E'"""
    User = apps.get_model("web_app", "User")
    User.objects.filter(identity="B").update(identity="E")


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0004_remove_user_groups_remove_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="identity",
            field=models.CharField(
                choices=[("A", "管理員"), ("E", "員工"), ("C", "顧客"), ("G", "訪客")],
                default="C",
                max_length=1,
            ),
        ),
        migrations.RunPython(migrate_employee_identity, migrations.RunPython.noop),
    ]
