# Generated by Django 5.1.6 on 2026-04-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0006_order_user_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="remark",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
