# Generated by Django 5.1.6 on 2026-04-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_order_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sno',
        ),
    ]
