# Generated by Django 5.1.6 on 2026-05-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0009_order_customer_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="notes",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
