# Generated by Django 5.1.6 on 2026-05-17 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0010_orderitem_notes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderitemoptions",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="notes",
        ),
        migrations.AddField(
            model_name="orderitemoptions",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web_app.orderitem",
            ),
        ),
        migrations.AlterField(
            model_name="orderitemoptions",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web_app.order",
            ),
        ),
    ]
