# Generated by Django 5.1.6 on 2026-05-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0013_db_integrity_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[(0, "等待中"), (1, "已完成"), (2, "已取消")], default=0
            ),
        ),
    ]
