# Generated by Django 5.1.6 on 2026-05-17 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0014_order_status_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="options",
            field=models.ManyToManyField(
                through="web_app.OptGroup", to="web_app.options"
            ),
        ),
        migrations.AlterField(
            model_name="optgroup",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opt_groups",
                to="web_app.menu",
            ),
        ),
        migrations.AlterField(
            model_name="optgroup",
            name="opt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opt_groups",
                to="web_app.options",
            ),
        ),
    ]
