# Generated by Django 5.1.6 on 2026-05-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0015_menu_options_m2m"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="menu",
            constraint=models.CheckConstraint(condition=models.Q(("price__gte", 0)), name="menu_price_non_negative"),
        ),
        migrations.AddConstraint(
            model_name="options",
            constraint=models.CheckConstraint(condition=models.Q(("price__gte", 0)), name="options_price_non_negative"),
        ),
    ]
