# Generated by Django 5.1.6 on 2026-05-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0016_price_non_negative_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
