# Generated by Django 6.0.3 on 2026-05-24 18:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0019_order_ready_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="create_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
