# Generated by Django 6.0.3 on 2026-05-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0022_rename_orderitemoptions"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["cart", "menu"], name="cartitem_cart_menu_idx"),
        ),
        migrations.AddIndex(
            model_name="menu",
            index=models.Index(fields=["type", "status"], name="menu_type_status_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer_phone"], name="order_customer_phone_idx"
            ),
        ),
    ]
