# Generated by Django 6.0.3 on 2026-05-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0026_store_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="options",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="options",
            name="is_custom_extra",
            field=models.BooleanField(default=False),
        ),
    ]
