# Generated by Django 6.0.3 on 2026-06-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0029_alter_user_email_order_order_status_created_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="today_sold_out",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
