# Generated by Django 6.0.3 on 2026-06-24 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0033_drop_cart_tables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="accepted_by",
        ),
    ]
