# Generated by Django 6.0.3 on 2026-06-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0036_storesettings_option_fk_seed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesettings',
            name='basil_option',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='cut_option',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='extra_ingredient_cost',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='garlic_option',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='spicy_option',
        ),
    ]
